name: My first workflow 
on: push    

jobs:  
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout stage
          uses: actions/checkout@v4

        - name: Install cowsay 
          run: |
            echo "My first Github actions job"
            sudo apt-get install cowsay -y
        
        - name: execute cowsay command
          run:  | 
            cowsay -f dragon "Run for cover, Iam a DRAGON-----RAWR" >> dragon.txt
        - name: sleep for 30 seconds
          run: sleep 30
    
    second_job:
      runs-on: ubuntu-latest
      steps:
      - name: sleep for 10 seconds
        run: sleep 10

      - name: test file exists
        run: grep -i "dragon" dragon.txt
      
    third_job:
      runs-on: ubuntu-latest
      steps:
      - name: Read the file
        run: cat dragon.txt

      - name: Deploy the file
        run: echo "deploying----"