name: My first workflow 
on: push    

jobs:  
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout stage
          uses: actions/checkout@v4

        - name: List and Read files
          run: |
            echo "My first Github actions job"
            ls -ltra
            cat README.md
            sudo apt-get install cowsay -y
        
        - name: Generate ASCII and execute cowsay command
          run:  | 
            cowsay -f dragon "Run for cover, Iam a DRAGON-----RAWR" >> dragon.txt
            grep -i "dragon" dragon.txt
            cat dragon.txt
            ls 
