name: My first workflow 
on: push    

jobs:  
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout stage
          uses: actions/checkout@v4

        - name: Install cowsay 
          run: |
            echo "My first Github actions job"
            sudo apt-get install cowsay -y
        
        - name: execute cowsay command
          run:  | 
            cowsay -f dragon "Run for cover, Iam a DRAGON-----RAWR" >> dragon.txt
        - name: Upload Dragon textfile
          uses: actions/upload-artifact@v4
          with:
            name: dragon-textfile
            path: dragon.txt

    
    second_job:
      needs: first_job
      runs-on: ubuntu-latest
      steps:
      - name: Download Dragon textfile
        uses: actions/download-artifact@v4
        with:
          name: dragon-textfile
      - name: test file exists
        run: grep -i "dragon" dragon.txt
      
    third_job:
      needs: second_job
      runs-on: ubuntu-latest
      steps:
      - name: Download Dragon textfile
        uses: actions/download-artifact@v4
        with:
          name: dragon-textfile
      
      - name: Read the file
        run: cat dragon.txt

      - name: Deploy the file
        run: echo "deploying----"