name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  CONTAINER_REGISTRY: docker.io
  DOCKER_USERNAME: manoharms
  IMAGE_NAME: github-actions-nginx

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # ✅ Ensures files are available

      - name: Verify directory structure
        run: ls -l  # ✅ Debugging step to check if actions-1 exists

      - name: Build Docker Image
        run: docker build -t $DOCKER_USERNAME/$IMAGE_NAME:latest .
    
      - name: Docker Login
        env:
          DOCKER_PASSWORD: "Zendevops@1"
        run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
    
      - name: Docker Publish
        run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Docker run
      run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$env.IMAGE_NAME:latest    