name: Exploring variables and secrets
on: #workflow level define env
  push

jobs:   #job-level define env
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Build
      env:                  #steplevel defined env
        CONTAINER_REGISTRY= docker.io  
        DOCKER_USERNAME= manoharms
        IMAGE_NAME= github-actions-nginx
      run: docker build -t ${{env.CONTAINER_REGISTRY}}/$DOCKER_USERNAME/$IMAGE_NAME:latest
    
    - name: Docker Login
      env:
        DOCKER_PASSWORD: Zendevops@1
        DOCKER_USERNAME: manoharms
      run: docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
    
    - name: Docker Publish
      env:
        CONTAINER_REGISTRY= docker.io
        DOCKER_USERNAME= manoharms
        IMAGE_NAME= github-actions-nginx
      run: docker push ${{env.CONTAINER_REGISTRY}}/$DOCKER_USERNAME/$IMAGE_NAME:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - name: Docker run
      env:
        CONTAINER_REGISTRY= docker.io
        DOCKER_USERNAME= manoharms
        IMAGE_NAME= github-actions-nginx
      run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest    