name: Exploring variables and secrets
on: push
env:          
  DOCKER_USERNAME= manoharms
  IMAGE_NAME= github-actions-nginx
jobs:   #job-level define env
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Build
      run: docker build -t ${{env.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:latest
    
    - name: Docker Login
      env:
        DOCKER_PASSWORD: Zendevops@1
      run: docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
    
    - name: Docker Publish
      env:
        DOCKER_USERNAME= manoharms
        IMAGE_NAME= github-actions-nginx
      run: docker push ${{env.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:latest

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Docker run
      run: echo docker run -d -p 8080:80 ${{env.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:latest    